# Generated by Django 2.1.4 on 2018-12-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('alignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('alignment_name', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'verbose_name': 'marvel heros alignment',
                'verbose_name_plural': 'marvel heros alignment',
                'db_table': 'alignments',
                'ordering': ['alignment_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('character_name', models.CharField(max_length=20, unique=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('character_number', models.CharField(max_length=8)),
                ('intelligence', models.IntegerField(blank=True, null=True)),
                ('strength', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('durability', models.IntegerField(blank=True, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('combat', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'character information',
                'verbose_name_plural': 'character information',
                'db_table': 'characters',
                'ordering': ['character_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterComic',
            fields=[
                ('character_comic_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'character comic relationship',
                'verbose_name_plural': 'character comic relationship',
                'db_table': 'character_comic',
                'ordering': ['character', 'comic'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterPower',
            fields=[
                ('character_power_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'character power relationship',
                'verbose_name_plural': 'character power relationship',
                'db_table': 'character_power',
                'ordering': ['character', 'power'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('comic_id', models.AutoField(primary_key=True, serialize=False)),
                ('comic_number', models.CharField(max_length=25, unique=True)),
                ('comic_name', models.CharField(max_length=25, unique=True)),
                ('issue_number', models.CharField(blank=True, max_length=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'comic information',
                'verbose_name_plural': 'comic information',
                'db_table': 'comics',
                'ordering': ['comic_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EyeColor',
            fields=[
                ('eye_color_id', models.AutoField(primary_key=True, serialize=False)),
                ('eye_color_name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'eye colors of marvel heros',
                'verbose_name_plural': 'eye colors of marvel heros ',
                'db_table': 'eye_colors',
                'ordering': ['eye_color_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('gender_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_name', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'verbose_name': 'gender of marvel heros',
                'verbose_name_plural': 'gender of marvel heros',
                'db_table': 'genders',
                'ordering': ['gender_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HairColor',
            fields=[
                ('hair_color_id', models.AutoField(primary_key=True, serialize=False)),
                ('hair_color_name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'hair colors of marvel heros',
                'verbose_name_plural': 'hair colors of marvel heros ',
                'db_table': 'hair_colors',
                'ordering': ['hair_color_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('power_id', models.AutoField(primary_key=True, serialize=False)),
                ('power_name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'super power information',
                'verbose_name_plural': 'super power information',
                'db_table': 'powers',
                'ordering': ['power_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisher_id', models.AutoField(primary_key=True, serialize=False)),
                ('publisher_name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'publishers of marvel heros',
                'verbose_name_plural': 'publishers of marvel heros ',
                'db_table': 'publisher',
                'ordering': ['publisher_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('race_id', models.AutoField(primary_key=True, serialize=False)),
                ('race_name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'races of marvel heros',
                'verbose_name_plural': 'races of marvel heros ',
                'db_table': 'race',
                'ordering': ['race_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkinColor',
            fields=[
                ('skin_color_id', models.AutoField(primary_key=True, serialize=False)),
                ('skin_color_name', models.CharField(max_length=25, unique=True)),
            ],
            options={
                'verbose_name': 'skin colors of marvel heros',
                'verbose_name_plural': 'skin colors of marvel heros ',
                'db_table': 'skin_color',
                'ordering': ['skin_color_name'],
                'managed': False,
            },
        ),
    ]
